#!/usr/bin/env ruby

$: << File.dirname(__FILE__) + "/lib"

require "rcgen"
include RcGen
RcGen.csv_file="data_def.csv"

if ARGV.size == 0
  eval STDIN.gets
else
  ARGV.each do|a|
    if a.match ".erb"
      require 'erb'
      template = ERB.new IO.read a
      puts template.result
    else
      eval IO.read a
    end
  end
end
