#!/usr/bin/env ruby

$: << File.dirname(__FILE__) + "/lib"

require "rcgen"
include RcGen

ARGV.each do|a|
  if a.match ".erb"
    require 'erb'
    template = ERB.new IO.read a
    puts template.result
  else
    eval IO.read a
  end
end
