#!/usr/bin/env ruby

require 'lib/rcgen.rb'
include RcGen

ARGV.each do|a|
  if a.match ".erb"
    require 'erb'
    template = ERB.new IO.read a
    puts template.result
  else
    eval IO.read a
  end
end
