#!/usr/bin/env ruby
$: << File.dirname(__FILE__) + "/lib"

require "rcsv"
include RCsv
template=ARGV[0]
input_csv=ARGV[1]

require 'rcgen'
include RcGen
require 'time'

RcGen.csv_file="data_def.csv"

def empty? value
  value.nil? || value.strip.empty? || value == '00/00/0000'
end

puts "SET BAIL ON;"
process template,input_csv
